import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbars from "./components/Navbars";
import Sidebar from "./components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
    
        <div className="flex">
{/* <Navbars /> */}
<Sidebar />

        <main className="flex-1">{children}</main>
          </div>
      
          </body>
    </html>
  );
}

 
{/* <div className="container mx-auto px-4 ">
<Navbars />
        <div  className="pb-8">{children}</div>
          </div> */}